### ISSUE TITLE
Custom CSS Support

### ISSUE THREAD

**Issue by p3lim** [darktrojan/newtabtools#339]
This is the only tab-replacer available that I liked, but the boxes are huge on a large display and the thumbnails get crazy distorted due to the scale.

Please allow custom CSS (like a box in the settings), so I can add something like this:
```css
#newtab-horizontal-margin {
	align-items: center;
	margin: auto;
}

Firefox prevents addons from adding stylesheets to other addons, so I can't do this from anywhere else.

**Comment by darktrojan** [comment]
You can use userContent.css if you're that desperate for custom CSS. Here's a simple example I just tested:

```css
@-moz-document url("moz-extension://cdea0cc6-fa00-4a9f-b60e-c011fa0decb9/newTab.xhtml") {
	body {
		display: none !important;
	}
}
```

Obviously, you'll need to change the URL to match.
